services:
  laravel:
    build:
      context: .
      args:
        APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    volumes:
      - ${LOCAL_PROJECT}:${APACHE_DOCUMENT_ROOT}
    ports:
      - ${LOCAL_PORT}:${CONTAINER_PORT}
  